name: Workflow tp
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
         php-version: '8.3'
         extensions: pgsql
      - name: Install dependencies
        run: composer install 
      
            
